apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server3
  labels:
    instance: third
    app: iperf
    type: server
spec:
  containers:
  - name: iperf3-server3
    image: narunask/networkstatic-iperf
    imagePullPolicy: IfNotPresent
    args: ['-s']
  nodeSelector:
    name: worker1
