apiVersion: v1
kind: Pod
metadata:
  name: iperf3-client5
  labels:
    instance: fifth
    app: iperf
spec:
  containers:
  - name: iperf3-client5
    image: narunask/networkstatic-iperf
    imagePullPolicy: IfNotPresent
    command: ['/bin/bash', '-c', 'sleep infinity']
  nodeSelector:
    name: worker3
