apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server5
  labels:
    instance: fifth
    app: iperf
    type: server
spec:
  containers:
  - name: iperf3-server5
    image: narunask/networkstatic-iperf
    imagePullPolicy: IfNotPresent
    args: ['-s']
  nodeSelector:
    name: worker1
